algoritmo "semnome"
var
a:inteiro
b , c, d, f: real
inicio
a<- abs(-50)
escreval ("valor absoluto: ",a )

b<- exp(9, 5)
escreval ("exponte: ",b)

c<- raizq(90)
escreval ("raiz quadrada: ",c)

c<- int(raizq(90))
escreval ("parte inteira da raiz quadrada: ",c)

d<- graupRad(90)
escreval ("conversao de garaus para radiano: ",d)

f<- sen(graupRad(90))
escreval ("conversao de garaus para radiano: ",f)

fimalgoritmo
